#!/usr/bin/env python3
""" Factor prime numbers """

from sys import argv
from math import sqrt


def fd(f_name):
    """reading from file and adding to array"""

    with open(f_name, "r", encoding="utf-8") as file:
        lines = file.readlines()
    n2f = []
    for line in lines:
        n2f.append(int(line))
    return n2f

def mult(n):
    """factoring n given numbers"""

    for i in range(1, n):
        if n == ((n // i) * i):
            print("{}={}*{}".format(n, (n // i), i))
            break

def factoring_list(ls):
    """factoring each number in list"""

    for i in ls:
        mult(i)

if len(argv) == 2:
    factoring_list(fd(argv[1]))
