#!/usr/bin/python3
"""RSA factoring ... continued"""

import sys

def factorize():
    """I kinda forgot how this works...kinda"""
    try:
        f_name = sys.argv[1]
        with open(f_name) as f:
            for ln in f:
                ln = int(ln)
                if ln % 2 == 0:
                        print("{}={}*{}".format(ln, ln // 2, 2))
                        continue
                i = 3
                while i < ln // 2:
                    if ln % i == 0:
                        print("{}={}*{}".format(ln, ln // i, i))
                        break
                    i = i + 2
                if i == (ln // 2) + 1:
                    print("{}={}*{}".format(ln, ln, 1))
    except (IndexError):
        pass
factorize()
