#!/usr/bin/python3
import sys
from sympy import factorint

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python rsa_factorization.py <file>")
        sys.exit(1)

    input_file = sys.argv[1]

    with open(input_file, 'r') as file:
        rsa_number = int(file.read().strip())
        factors = factorint(rsa_number)
        p, q = factors.keys()
        print(f"RSA number: {rsa_number}")
        print(f"p = {p}, q = {q}")

